server:
  port: 8761
spring:
  profiles:
    active: "dev"
  application:
    name: eureka

---

spring:
  profiles: dev
eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

---

spring:
  profiles: prod
eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}